#!/bin/sh
REPO_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
REPO_NAME="zestiso"
echo "[UPDATE] Creating $REPO_NAME DB"

# Delete old files
rm -f "$REPO_DIR"/*.db "$REPO_DIR"/*.files "$REPO_DIR"/*.sig "$REPO_DIR"/*.tar.gz &> /dev/null

# Sign all packages
#for FILE in $(ls "$REPO_DIR"/*.pkg.tar.zst); do
#	gpg --use-agent --output "$FILE.sig" --detach-sig "$FILE"
#done

# Create repo and add packages (everything is signed)
#repo-add --verify --sign "$REPO_DIR/$REPO_NAME.db.tar.gz" "$REPO_DIR"/*.pkg.tar.zst
repo-add --verify "$REPO_DIR/$REPO_NAME.db.tar.gz" "$REPO_DIR"/*.pkg.tar.zst

# Delete/rename files for pacman
rm $REPO_NAME.db $REPO_NAME.files &> /dev/null
mv $REPO_NAME.db.tar.gz $REPO_NAME.db &> /dev/null
mv $REPO_NAME.files.tar.gz $REPO_NAME.files &> /dev/null
mv $REPO_NAME.db.tar.gz.sig $REPO_NAME.db.sig &> /dev/null
mv $REPO_NAME.files.tar.gz.sig $REPO_NAME.files.sig &> /dev/null

git add . && \
git commit -m "General stability and performance improvements to optimise user experience" && \
git push -u origin main
